import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import SidebarProvider from "@/context/SidebarContext";
import { Toaster } from "react-hot-toast";
import FolderProvider from "@/context/FolderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-midnight`}
        >
          <FolderProvider>
            <SidebarProvider>
              <Header />
              <Sidebar />
            </SidebarProvider>
            <div className="absolute top-16 md:left-64 p-5 w-full md:w-[calc(100vw-256px)]">
              {children}
            </div>
            <Toaster />
          </FolderProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
