import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import PreviewModal from "@/components/PreviewModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-midnight`}
        >
          <Header />
          <Sidebar />

          <div className="absolute top-16 md:left-64 p-5 w-full md:w-[calc(100vw-276px)] h-[calc(100vh-64px)]">
            {children}
          </div>
          <Toaster />
          <PreviewModal />
        </body>
      </html>
    </ClerkProvider>
  );
}
